### ISSUE TITLE
Trunk doesn't compile

### ISSUE THREAD

**Issue by docdawning** [jetty840/ReplicatorG#62]
I've downloaded your head state and tried to compile it on fresh Ubuntu 14.10 (Fully updated as of 2015-01-27). I get the following build message:
```
j@j-virtual-machine:~/MakerBot/HostSoftware/ReplicatorG/jetty840/ReplicatorG-master$ ./run-from-git.sh 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Buildfile: /home/j/MakerBot/HostSoftware/ReplicatorG/jetty840/ReplicatorG-master/build.xml
     [echo] Linux-amd64

compile:
    [javac] Compiling 1 source file to /home/j/MakerBot/HostSoftware/ReplicatorG/jetty840/ReplicatorG-master/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
    [javac] 1 warning

jar:
      [jar] Building jar: /home/j/MakerBot/HostSoftware/ReplicatorG/jetty840/ReplicatorG-master/build/jar/ReplicatorG.jar

run:
     [java] Jan 27, 2015 11:00:22 PM replicatorg.machine.MachineFactory load
     [java] SEVERE: Could not load machine 'The Replicator Dual' no machineNode found
     [java] java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
     [java] Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
     [java] 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
     [java] 	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
     [java] 	at java.lang.System.loadLibrary(System.java:1088)
     [java] 	at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
     [java] 	at replicatorg.app.util.serial.Serial.scanSerialNames(Serial.java:103)
     [java] 	at replicatorg.app.ui.MainWindow.reloadSerialMenu(MainWindow.java:691)
     [java] 	at replicatorg.app.ui.MainWindow.buildMachineMenu(MainWindow.java:1247)
     [java] 	at replicatorg.app.ui.MainWindow.<init>(MainWindow.java:334)
     [java] 	at replicatorg.app.Base$2.run(Base.java:656)
     [java] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
     [java] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
     [java] 	at java.awt.EventQueue.access$300(EventQueue.java:103)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:699)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:697)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
     [java] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
     [java] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
     [java] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by dcnewman** [comment]
That's not how you build it.

Use ant.  I have no idea what that shell script is.  MBI left a lot of dross in the repo.
